apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator-server
  template:
    metadata:
      labels:
        app: data-generator-server
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: data-generator-server
          image: ghcr.io/nhnacademy-aiot3-yes-ai-do/data_generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: data-generator-config
            - secretRef:
                name: backend-domain-secret
            - secretRef:
                name: data-generator-secret
            - secretRef:
                name: log-secret
            - secretRef:
                name: mqtt-secret
