apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-generator-server
  template:
    metadata:
      labels:
        app: data-generator-server
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: data-generator-server
          image: ghcr.io/nhnacademy-aiot3-yes-ai-do/data-generator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: data-generator-config