apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultivation-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cultivation-server
  template:
    metadata:
      labels:
        app: cultivation-server
    spec:
      serviceAccountName: backend-sa
      hostAliases:
        - ip: "10.116.64.12"
          hostnames:
            - "storage.java21.net"
      containers:
        - name: cultivation-server
          image: ghcr.io/nhnacademy-aiot3-yes-ai-do/cultivation_server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cultivation-config
            - secretRef:
                name: backend-domain-secret
            - secretRef:
                name: cultivation-secret
            - secretRef:
                name: log-secret
            - secretRef:
                name: postgresdb-secret
            - secretRef:
                name: rabbitmq-secret
            - secretRef:
                name: influxdb-secret
            - secretRef:
                name: minio-secret
