apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: ghcr.io/nhnacademy-aiot3-yes-ai-do/user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: base-secret
            - secretRef:
                name: user-secret
