apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-server
  template:
    metadata:
      labels:
        app: notification-server
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: notification-server
          image: ghcr.io/nhnacademy-aiot3-yes-ai-do/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: backend-domain-secret
            - secretRef:
                name: notification-secret
            - secretRef:
                name: log-secret
            - secretRef:
                name: postgredb-secret
            - secretRef:
                name: rabbitmq-secret
